#!/usr/bin/env python3
"""Generates typed string accessors for both apps from strings.json.

    shared/localization/generate.py           write the generated files
    shared/localization/generate.py --check   fail if they're out of date (CI)

Each entry becomes a property (no arguments) or a function (with arguments) that returns the
string in the current language, e.g. L10n.toReviewTab(n: 3) in Swift, L10n.ToReviewTab(3) in C#.
"{name}" in a string is replaced by the argument of that name; other braces are literal.
An English value can be {"one": ..., "other": ...} for strings with a count argument "n".
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = Path(__file__).with_name("strings.json")
SWIFT_OUT = ROOT / "macos/PRChecker/L10n.swift"
CSHARP_OUT = ROOT / "windows/src/PRChecker.Core/L10n.cs"
HEADER = "Generated by shared/localization/generate.py from strings.json. Don't edit; change strings.json and rerun."


def placeholders(text, args):
    """Splits text into literal parts and argument names, in order."""
    parts, last = [], 0
    for match in re.finditer(r"\{(\w+)\}", text):
        if match.group(1) in args:
            parts.append(("text", text[last:match.start()]))
            parts.append(("arg", match.group(1)))
            last = match.end()
    parts.append(("text", text[last:]))
    return parts


def variants(entry, language):
    value = entry[language]
    return value if isinstance(value, dict) else {"other": value}


# MARK: Swift

def swift_literal(text, args):
    out = []
    for kind, value in placeholders(text, args):
        if kind == "arg":
            out.append(f"\\({value})")
        else:
            out.append(value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\\(", "\\\\("))
    return '"' + "".join(out) + '"'


def swift_value(entry, language, args):
    forms = variants(entry, language)
    if "one" in forms:
        return f'n == 1 ? {swift_literal(forms["one"], args)} : {swift_literal(forms["other"], args)}'
    return swift_literal(forms["other"], args)


def swift(entries):
    lines = [f"// {HEADER}", "", "import Foundation", "",
             "/// Every user-facing string, in the current `Localizer` language. Usable from any thread.",
             "nonisolated enum L10n {"]
    for entry in entries:
        args = entry.get("args", {})
        english = variants(entry, "en")["other"].replace("\n", " ")
        lines.append(f"    /// {english}")
        body = [
            "        switch Localizer.current {",
            f"        case .english: {swift_value(entry, 'en', args)}",
            f"        case .turkish: {swift_value(entry, 'tr', args)}",
            "        }",
        ]
        if args:
            params = ", ".join(f"{name}: {'Int' if kind == 'int' else 'String'}" for name, kind in args.items())
            lines.append(f"    static func {entry['id']}({params}) -> String {{")
        else:
            lines.append(f"    static var {entry['id']}: String {{")
        lines += body + ["    }", ""]
    lines[-1] = "}"
    return "\n".join(lines) + "\n"


# MARK: C#

def csharp_literal(text, args):
    parts = placeholders(text, args)
    interpolated = any(kind == "arg" for kind, _ in parts)
    out = []
    for kind, value in parts:
        if kind == "arg":
            out.append("{" + value + "}")
        else:
            escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
            out.append(escaped.replace("{", "{{").replace("}", "}}") if interpolated else escaped)
    return ("$" if interpolated else "") + '"' + "".join(out) + '"'


def csharp_value(entry, language, args):
    forms = variants(entry, language)
    if "one" in forms:
        return f'n == 1 ? {csharp_literal(forms["one"], args)} : {csharp_literal(forms["other"], args)}'
    return csharp_literal(forms["other"], args)


def pascal(name):
    return name[0].upper() + name[1:]


def csharp(entries):
    lines = [f"// <auto-generated>{HEADER}</auto-generated>", "", "namespace PRChecker.Core;", "",
             "/// <summary>Every user-facing string, in the current <see cref=\"Localizer.Language\"/>.</summary>",
             "public static class L10n", "{"]
    for entry in entries:
        args = entry.get("args", {})
        english = variants(entry, "en")["other"].replace("\n", " ").replace("&", "&amp;").replace("<", "&lt;")
        lines.append(f"    /// <summary>{english}</summary>")
        value = (f"Localizer.Language == AppLanguage.Turkish\n            ? {csharp_value(entry, 'tr', args)}\n"
                 f"            : {csharp_value(entry, 'en', args)};")
        if args:
            params = ", ".join(f"{'int' if kind == 'int' else 'string'} {name}" for name, kind in args.items())
            lines.append(f"    public static string {pascal(entry['id'])}({params}) =>\n        {value}")
        else:
            lines.append(f"    public static string {pascal(entry['id'])} =>\n        {value}")
        lines.append("")
    lines[-1] = "}"
    return "\n".join(lines) + "\n"


def main():
    document = json.loads(SOURCE.read_text(encoding="utf-8"))
    entries = document["strings"]
    for entry in entries:
        for language in document["languages"]:
            if language not in entry:
                sys.exit(f"{entry['id']}: missing {language}")
        if any(isinstance(entry[l], dict) for l in document["languages"]) and "n" not in entry.get("args", {}):
            sys.exit(f"{entry['id']}: plural forms need an int argument 'n'")
        # Every form in every language must use exactly the declared arguments.
        args = set(entry.get("args", {}))
        for language in document["languages"]:
            for form, text in variants(entry, language).items():
                used = {name for name in re.findall(r"\{(\w+)\}", text) if name in args}
                if used != args:
                    sys.exit(f"{entry['id']} ({language}, {form}): uses {sorted(used)}, expected {sorted(args)}")

    outputs = {
        SWIFT_OUT: swift([e for e in entries if "macos" in e["platforms"]]),
        CSHARP_OUT: csharp([e for e in entries if "windows" in e["platforms"]]),
    }
    if "--check" in sys.argv:
        stale = [str(path.relative_to(ROOT)) for path, text in outputs.items()
                 if not path.exists() or path.read_text(encoding="utf-8") != text]
        if stale:
            sys.exit("Out of date (run shared/localization/generate.py): " + ", ".join(stale))
        print("Generated strings are up to date.")
        return
    for path, text in outputs.items():
        path.write_text(text, encoding="utf-8")
        print(f"Wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
