// Generated by shared/localization/generate.py from strings.json. Don't edit; change strings.json and rerun.

import Foundation

/// Every user-facing string, in the current `Localizer` language. Usable from any thread.
nonisolated enum L10n {
    /// To review ({n})
    static func toReviewTab(n: Int) -> String {
        switch Localizer.current {
        case .english: "To review (\(n))"
        case .turkish: "İncelenecek (\(n))"
        }
    }

    /// Mine ({n})
    static func mineTab(n: Int) -> String {
        switch Localizer.current {
        case .english: "Mine (\(n))"
        case .turkish: "PR'larım (\(n))"
        }
    }

    /// List
    static var listPicker: String {
        switch Localizer.current {
        case .english: "List"
        case .turkish: "Liste"
        }
    }

    /// Nothing to review
    static var nothingToReview: String {
        switch Localizer.current {
        case .english: "Nothing to review"
        case .turkish: "İncelenecek bir şey yok"
        }
    }

    /// No open pull requests
    static var noOpenPullRequests: String {
        switch Localizer.current {
        case .english: "No open pull requests"
        case .turkish: "Açık PR yok"
        }
    }

    /// Can't load pull requests
    static var cantLoadPullRequests: String {
        switch Localizer.current {
        case .english: "Can't load pull requests"
        case .turkish: "PR'lar yüklenemedi"
        }
    }

    /// Open Settings
    static var openSettings: String {
        switch Localizer.current {
        case .english: "Open Settings"
        case .turkish: "Ayarları aç"
        }
    }

    /// Updated {time}
    static func updatedAgo(time: String) -> String {
        switch Localizer.current {
        case .english: "Updated \(time)"
        case .turkish: "\(time) güncellendi"
        }
    }

    /// Refresh
    static var refresh: String {
        switch Localizer.current {
        case .english: "Refresh"
        case .turkish: "Yenile"
        }
    }

    /// Settings
    static var settings: String {
        switch Localizer.current {
        case .english: "Settings"
        case .turkish: "Ayarlar"
        }
    }

    /// Quit
    static var quit: String {
        switch Localizer.current {
        case .english: "Quit"
        case .turkish: "Çık"
        }
    }

    /// Quit PR Checker
    static var quitApp: String {
        switch Localizer.current {
        case .english: "Quit PR Checker"
        case .turkish: "PR Checker'dan çık"
        }
    }

    /// Quit PR Checker?
    static var quitConfirmTitle: String {
        switch Localizer.current {
        case .english: "Quit PR Checker?"
        case .turkish: "PR Checker'dan çıkılsın mı?"
        }
    }

    /// You won't see pull requests or get notifications until you open it again.
    static var quitConfirmMessage: String {
        switch Localizer.current {
        case .english: "You won't see pull requests or get notifications until you open it again."
        case .turkish: "Uygulamayı yeniden açana kadar PR'ları göremez ve bildirim almazsınız."
        }
    }

    /// Cancel
    static var cancel: String {
        switch Localizer.current {
        case .english: "Cancel"
        case .turkish: "İptal"
        }
    }

    /// Notifications are off in System Settings
    static var notificationsOffMac: String {
        switch Localizer.current {
        case .english: "Notifications are off in System Settings"
        case .turkish: "Bildirimler Sistem Ayarları'nda kapalı"
        }
    }

    /// Notifications are turned off for PR Checker in System Settings. Click to fix.
    static var notificationsOffMacHelp: String {
        switch Localizer.current {
        case .english: "Notifications are turned off for PR Checker in System Settings. Click to fix."
        case .turkish: "PR Checker bildirimleri Sistem Ayarları'nda kapalı. Düzeltmek için tıklayın."
        }
    }

    /// Open notification settings
    static var openNotificationSettings: String {
        switch Localizer.current {
        case .english: "Open notification settings"
        case .turkish: "Bildirim ayarlarını aç"
        }
    }

    /// Draft
    static var badgeDraft: String {
        switch Localizer.current {
        case .english: "Draft"
        case .turkish: "Taslak"
        }
    }

    /// New commits
    static var badgeNewCommits: String {
        switch Localizer.current {
        case .english: "New commits"
        case .turkish: "Yeni commit'ler"
        }
    }

    /// Needs work
    static var needsWork: String {
        switch Localizer.current {
        case .english: "Needs work"
        case .turkish: "Değişiklik gerekli"
        }
    }

    /// Conflicts
    static var badgeConflicts: String {
        switch Localizer.current {
        case .english: "Conflicts"
        case .turkish: "Çakışmalar"
        }
    }

    /// Build
    static var badgeBuild: String {
        switch Localizer.current {
        case .english: "Build"
        case .turkish: "Derleme"
        }
    }

    /// Approved
    static var reviewerApproved: String {
        switch Localizer.current {
        case .english: "Approved"
        case .turkish: "Onayladı"
        }
    }

    /// Not reviewed
    static var reviewerNotReviewed: String {
        switch Localizer.current {
        case .english: "Not reviewed"
        case .turkish: "İncelemedi"
        }
    }

    /// PR Checker Settings
    static var settingsWindowTitle: String {
        switch Localizer.current {
        case .english: "PR Checker Settings"
        case .turkish: "PR Checker Ayarları"
        }
    }

    /// General
    static var tabGeneral: String {
        switch Localizer.current {
        case .english: "General"
        case .turkish: "Genel"
        }
    }

    /// Bitbucket
    static var tabBitbucket: String {
        switch Localizer.current {
        case .english: "Bitbucket"
        case .turkish: "Bitbucket"
        }
    }

    /// About
    static var tabAbout: String {
        switch Localizer.current {
        case .english: "About"
        case .turkish: "Hakkında"
        }
    }

    /// Notifications
    static var notifications: String {
        switch Localizer.current {
        case .english: "Notifications"
        case .turkish: "Bildirimler"
        }
    }

    /// Turned off in System Settings
    static var blockedMacTitle: String {
        switch Localizer.current {
        case .english: "Turned off in System Settings"
        case .turkish: "Sistem Ayarları'nda kapalı"
        }
    }

    /// macOS is blocking PR Checker's notifications. Turn on Allow Notifications.
    static var blockedMacMessage: String {
        switch Localizer.current {
        case .english: "macOS is blocking PR Checker's notifications. Turn on Allow Notifications."
        case .turkish: "macOS, PR Checker bildirimlerini engelliyor. \"Bildirimlere izin ver\"i açın."
        }
    }

    /// Check delivery
    static var checkDelivery: String {
        switch Localizer.current {
        case .english: "Check delivery"
        case .turkish: "Bildirim testi"
        }
    }

    /// Send Test Notification
    static var sendTestNotification: String {
        switch Localizer.current {
        case .english: "Send Test Notification"
        case .turkish: "Test bildirimi gönder"
        }
    }

    /// Show pull request details
    static var showDetails: String {
        switch Localizer.current {
        case .english: "Show pull request details"
        case .turkish: "PR ayrıntılarını göster"
        }
    }

    /// Off: notifications don't show titles, names or results, e.g. while screen sharing.
    static var showDetailsHint: String {
        switch Localizer.current {
        case .english: "Off: notifications don't show titles, names or results, e.g. while screen sharing."
        case .turkish: "Kapalıyken bildirimler başlık, isim veya sonuç göstermez; örneğin ekran paylaşırken."
        }
    }

    /// Open at login
    static var openAtLogin: String {
        switch Localizer.current {
        case .english: "Open at login"
        case .turkish: "Oturum açılınca başlat"
        }
    }

    /// Refresh
    static var refreshSection: String {
        switch Localizer.current {
        case .english: "Refresh"
        case .turkish: "Yenileme"
        }
    }

    /// Check every
    static var checkEvery: String {
        switch Localizer.current {
        case .english: "Check every"
        case .turkish: "Kontrol sıklığı"
        }
    }

    /// {n} min
    static func minutesShort(n: Int) -> String {
        switch Localizer.current {
        case .english: "\(n) min"
        case .turkish: "\(n) dk"
        }
    }

    /// Language
    static var language: String {
        switch Localizer.current {
        case .english: "Language"
        case .turkish: "Dil"
        }
    }

    /// System language
    static var languageSystem: String {
        switch Localizer.current {
        case .english: "System language"
        case .turkish: "Sistem dili"
        }
    }

    /// Server URL
    static var serverURL: String {
        switch Localizer.current {
        case .english: "Server URL"
        case .turkish: "Sunucu adresi"
        }
    }

    /// Access token
    static var accessToken: String {
        switch Localizer.current {
        case .english: "Access token"
        case .turkish: "Token"
        }
    }

    /// Saved – leave empty to keep
    static var tokenSavedPlaceholder: String {
        switch Localizer.current {
        case .english: "Saved – leave empty to keep"
        case .turkish: "Kayıtlı – değiştirmemek için boş bırakın"
        }
    }

    /// Required
    static var tokenRequiredPlaceholder: String {
        switch Localizer.current {
        case .english: "Required"
        case .turkish: "Gerekli"
        }
    }

    /// Save & Connect
    static var saveAndConnect: String {
        switch Localizer.current {
        case .english: "Save & Connect"
        case .turkish: "Kaydet ve bağlan"
        }
    }

    /// Connected as {name}
    static func connectedAs(name: String) -> String {
        switch Localizer.current {
        case .english: "Connected as \(name)"
        case .turkish: "\(name) olarak bağlanıldı"
        }
    }

    /// Sign Out
    static var signOut: String {
        switch Localizer.current {
        case .english: "Sign Out"
        case .turkish: "Oturumu kapat"
        }
    }

    /// Sign out of Bitbucket?
    static var signOutConfirmTitle: String {
        switch Localizer.current {
        case .english: "Sign out of Bitbucket?"
        case .turkish: "Bitbucket oturumu kapatılsın mı?"
        }
    }

    /// Removes the access token from your Keychain and the pull request data PR Checker stored for this server.
    static var signOutConfirmMessageMac: String {
        switch Localizer.current {
        case .english: "Removes the access token from your Keychain and the pull request data PR Checker stored for this server."
        case .turkish: "Bu sunucunun token'ını Anahtar Zinciri'nden ve PR Checker'ın sakladığı PR verilerini siler."
        }
    }

    /// Create a token under Profile → Manage account → HTTP access tokens with Read permission. It is stored in your Keychain and only sent to this server.
    static var tokenHintMac: String {
        switch Localizer.current {
        case .english: "Create a token under Profile → Manage account → HTTP access tokens with Read permission. It is stored in your Keychain and only sent to this server."
        case .turkish: "Bitbucket'ta Profile → Manage account → HTTP access tokens altında Read izinli bir token oluşturun. Token Anahtar Zinciri'nde saklanır ve yalnızca bu sunucuya gönderilir."
        }
    }

    /// Filters
    static var filters: String {
        switch Localizer.current {
        case .english: "Filters"
        case .turkish: "Filtreler"
        }
    }

    /// Hide draft pull requests
    static var hideDrafts: String {
        switch Localizer.current {
        case .english: "Hide draft pull requests"
        case .turkish: "Taslak PR'ları gizle"
        }
    }

    /// Only these projects/repos
    static var onlyTheseRepos: String {
        switch Localizer.current {
        case .english: "Only these projects/repos"
        case .turkish: "Yalnızca bu projeler/repolar"
        }
    }

    /// All
    static var filterAllPlaceholder: String {
        switch Localizer.current {
        case .english: "All"
        case .turkish: "Tümü"
        }
    }

    /// Comma-separated project keys or PROJECT/repo-slug, e.g. PROJ, OTHER/my-repo.
    static var filterHint: String {
        switch Localizer.current {
        case .english: "Comma-separated project keys or PROJECT/repo-slug, e.g. PROJ, OTHER/my-repo."
        case .turkish: "Virgülle ayrılmış proje anahtarları veya PROJE/repo-slug, örn. PROJ, OTHER/my-repo."
        }
    }

    /// Version
    static var version: String {
        switch Localizer.current {
        case .english: "Version"
        case .turkish: "Sürüm"
        }
    }

    /// Updates
    static var updates: String {
        switch Localizer.current {
        case .english: "Updates"
        case .turkish: "Güncellemeler"
        }
    }

    /// Check for Updates
    static var checkForUpdates: String {
        switch Localizer.current {
        case .english: "Check for Updates"
        case .turkish: "Güncellemeleri kontrol et"
        }
    }

    /// Last checked {time}
    static func lastChecked(time: String) -> String {
        switch Localizer.current {
        case .english: "Last checked \(time)"
        case .turkish: "Son kontrol: \(time)"
        }
    }

    /// Checked automatically once a week
    static var checkedWeekly: String {
        switch Localizer.current {
        case .english: "Checked automatically once a week"
        case .turkish: "Haftada bir otomatik kontrol edilir"
        }
    }

    /// Automation
    static var automation: String {
        switch Localizer.current {
        case .english: "Automation"
        case .turkish: "Otomasyon"
        }
    }

    /// Run a command for new review requests
    static var automationToggle: String {
        switch Localizer.current {
        case .english: "Run a command for new review requests"
        case .turkish: "Yeni inceleme istekleri için komut çalıştır"
        }
    }

    /// Once per commit for pull requests in To review, e.g. to start an automated pre-check.
    static var automationToggleHint: String {
        switch Localizer.current {
        case .english: "Once per commit for pull requests in To review, e.g. to start an automated pre-check."
        case .turkish: "İncelenecek listesindeki PR'lar için her commit'te bir kez; örneğin otomatik bir ön kontrol başlatmak için."
        }
    }

    /// Command
    static var command: String {
        switch Localizer.current {
        case .english: "Command"
        case .turkish: "Komut"
        }
    }

    /// Not set
    static var notSet: String {
        switch Localizer.current {
        case .english: "Not set"
        case .turkish: "Ayarlanmadı"
        }
    }

    /// Set Command
    static var setCommand: String {
        switch Localizer.current {
        case .english: "Set Command"
        case .turkish: "Komutu ayarla"
        }
    }

    /// Edit
    static var edit: String {
        switch Localizer.current {
        case .english: "Edit"
        case .turkish: "Düzenle"
        }
    }

    /// Run Now
    static var runNow: String {
        switch Localizer.current {
        case .english: "Run Now"
        case .turkish: "Şimdi çalıştır"
        }
    }

    /// Show Log
    static var showLog: String {
        switch Localizer.current {
        case .english: "Show Log"
        case .turkish: "Günlüğü göster"
        }
    }

    /// Last run
    static var lastRun: String {
        switch Localizer.current {
        case .english: "Last run"
        case .turkish: "Son çalıştırma"
        }
    }

    /// Run the command for {n} pull requests now?
    static func runAllQuestion(n: Int) -> String {
        switch Localizer.current {
        case .english: "Run the command for \(n) pull requests now?"
        case .turkish: "Komut şimdi \(n) PR için çalıştırılsın mı?"
        }
    }

    /// Every pull request in To review, including commits it already ran for.
    static var runAllHint: String {
        switch Localizer.current {
        case .english: "Every pull request in To review, including commits it already ran for."
        case .turkish: "İncelenecek listesindeki tüm PR'lar; daha önce çalıştırıldığı commit'ler dahil."
        }
    }

    /// Run the command for the {n} pull requests waiting now?
    static func backlogQuestion(n: Int) -> String {
        switch Localizer.current {
        case .english: n == 1 ? "Run the command for the \(n) pull request waiting now?" : "Run the command for the \(n) pull requests waiting now?"
        case .turkish: "Bekleyen \(n) PR için komut şimdi çalıştırılsın mı?"
        }
    }

    /// They're already in your review list. The command may post comments on them.
    static var backlogHint: String {
        switch Localizer.current {
        case .english: "They're already in your review list. The command may post comments on them."
        case .turkish: "Bunlar zaten inceleme listenizde. Komut bu PR'lara yorum ekleyebilir."
        }
    }

    /// Run for {n} Pull Requests
    static func runForCount(n: Int) -> String {
        switch Localizer.current {
        case .english: "Run for \(n) Pull Requests"
        case .turkish: "\(n) PR için çalıştır"
        }
    }

    /// Only New Ones From Now
    static var onlyNewOnes: String {
        switch Localizer.current {
        case .english: "Only New Ones From Now"
        case .turkish: "Yalnızca bundan sonrakiler"
        }
    }

    /// Running for {n} pull requests…
    static func runningFor(n: Int) -> String {
        switch Localizer.current {
        case .english: n == 1 ? "Running for \(n) pull request…" : "Running for \(n) pull requests…"
        case .turkish: "\(n) PR için çalışıyor…"
        }
    }

    /// Not run since PR Checker started
    static var notRunYet: String {
        switch Localizer.current {
        case .english: "Not run since PR Checker started"
        case .turkish: "PR Checker açıldığından beri çalıştırılmadı"
        }
    }

    /// running
    static var outcomeRunning: String {
        switch Localizer.current {
        case .english: "running"
        case .turkish: "çalışıyor"
        }
    }

    /// finished
    static var outcomeFinished: String {
        switch Localizer.current {
        case .english: "finished"
        case .turkish: "tamamlandı"
        }
    }

    /// failed (exit {code})
    static func outcomeFailed(code: Int) -> String {
        switch Localizer.current {
        case .english: "failed (exit \(code))"
        case .turkish: "başarısız (çıkış kodu \(code))"
        }
    }

    /// couldn't start: {error}
    static func couldntStart(error: String) -> String {
        switch Localizer.current {
        case .english: "couldn't start: \(error)"
        case .turkish: "başlatılamadı: \(error)"
        }
    }

    /// Automation Command
    static var automationCommandTitle: String {
        switch Localizer.current {
        case .english: "Automation Command"
        case .turkish: "Otomasyon komutu"
        }
    }

    /// Runs once per commit for pull requests in To review. Placeholders are filled into each argument; nothing goes through a shell.
    static var automationCommandHint: String {
        switch Localizer.current {
        case .english: "Runs once per commit for pull requests in To review. Placeholders are filled into each argument; nothing goes through a shell."
        case .turkish: "İncelenecek listesindeki PR'lar için her commit'te bir kez çalışır. Yer tutucular her argümana ayrı ayrı yerleştirilir; hiçbir şey kabuk (shell) üzerinden çalıştırılmaz."
        }
    }

    /// Insert
    static var insert: String {
        switch Localizer.current {
        case .english: "Insert"
        case .turkish: "Ekle"
        }
    }

    /// Arguments for {id}
    static func argumentsFor(id: String) -> String {
        switch Localizer.current {
        case .english: "Arguments for \(id)"
        case .turkish: "\(id) için argümanlar"
        }
    }

    /// Arguments for an example pull request
    static var argumentsForExample: String {
        switch Localizer.current {
        case .english: "Arguments for an example pull request"
        case .turkish: "Örnek bir PR için argümanlar"
        }
    }

    /// Enter a command, e.g. /usr/bin/python3 ~/bin/check.py --pr {link} --commit {commit}
    static var enterCommandExample: String {
        switch Localizer.current {
        case .english: "Enter a command, e.g. /usr/bin/python3 ~/bin/check.py --pr {link} --commit {commit}"
        case .turkish: "Bir komut girin, örn. /usr/bin/python3 ~/bin/check.py --pr {link} --commit {commit}"
        }
    }

    /// Clear
    static var clear: String {
        switch Localizer.current {
        case .english: "Clear"
        case .turkish: "Temizle"
        }
    }

    /// Save
    static var save: String {
        switch Localizer.current {
        case .english: "Save"
        case .turkish: "Kaydet"
        }
    }

    /// Enter a command.
    static var enterCommand: String {
        switch Localizer.current {
        case .english: "Enter a command."
        case .turkish: "Bir komut girin."
        }
    }

    /// The command has an unterminated quote.
    static var unterminatedQuote: String {
        switch Localizer.current {
        case .english: "The command has an unterminated quote."
        case .turkish: "Komutta kapatılmamış bir tırnak var."
        }
    }

    /// Review requested by {author}
    static func notifyReviewRequested(author: String) -> String {
        switch Localizer.current {
        case .english: "Review requested by \(author)"
        case .turkish: "\(author) inceleme istedi"
        }
    }

    /// New commits to re-review
    static var notifyNewCommits: String {
        switch Localizer.current {
        case .english: "New commits to re-review"
        case .turkish: "Yeniden incelenecek yeni commit'ler"
        }
    }

    /// ✅ Approved by {name}
    static func notifyApproved(name: String) -> String {
        switch Localizer.current {
        case .english: "✅ Approved by \(name)"
        case .turkish: "✅ \(name) onayladı"
        }
    }

    /// ✋ {name} marked it needs work
    static func notifyNeedsWork(name: String) -> String {
        switch Localizer.current {
        case .english: "✋ \(name) marked it needs work"
        case .turkish: "✋ \(name) değişiklik istedi"
        }
    }

    /// ⚠️ Merge conflicts
    static var notifyConflicts: String {
        switch Localizer.current {
        case .english: "⚠️ Merge conflicts"
        case .turkish: "⚠️ Birleştirme çakışmaları"
        }
    }

    /// 🔧 Conflicts resolved
    static var notifyConflictsResolved: String {
        switch Localizer.current {
        case .english: "🔧 Conflicts resolved"
        case .turkish: "🔧 Çakışmalar çözüldü"
        }
    }

    /// ❌ Build failed
    static var notifyBuildFailed: String {
        switch Localizer.current {
        case .english: "❌ Build failed"
        case .turkish: "❌ Derleme başarısız"
        }
    }

    /// ✅ Build fixed
    static var notifyBuildFixed: String {
        switch Localizer.current {
        case .english: "✅ Build fixed"
        case .turkish: "✅ Derleme düzeldi"
        }
    }

    /// 💬 {n} new comments from {names}
    static func notifyComments(n: Int, names: String) -> String {
        switch Localizer.current {
        case .english: n == 1 ? "💬 \(n) new comment from \(names)" : "💬 \(n) new comments from \(names)"
        case .turkish: "💬 \(n) yeni yorum: \(names)"
        }
    }

    /// 🎉 Merged
    static var notifyMerged: String {
        switch Localizer.current {
        case .english: "🎉 Merged"
        case .turkish: "🎉 Birleştirildi"
        }
    }

    /// 🚫 Declined
    static var notifyDeclined: String {
        switch Localizer.current {
        case .english: "🚫 Declined"
        case .turkish: "🚫 Reddedildi"
        }
    }

    /// No longer open
    static var notifyNoLongerOpen: String {
        switch Localizer.current {
        case .english: "No longer open"
        case .turkish: "Artık açık değil"
        }
    }

    /// PR Checker notifications work
    static var testNotificationTitle: String {
        switch Localizer.current {
        case .english: "PR Checker notifications work"
        case .turkish: "PR Checker bildirimleri çalışıyor"
        }
    }

    /// Click a notification to open its pull request.
    static var testNotificationBody: String {
        switch Localizer.current {
        case .english: "Click a notification to open its pull request."
        case .turkish: "PR'ı açmak için bildirime tıklayın."
        }
    }

    /// A pull request has an update. Click to open it.
    static var privateNotificationBody: String {
        switch Localizer.current {
        case .english: "A pull request has an update. Click to open it."
        case .turkish: "Bir PR'da güncelleme var. Açmak için tıklayın."
        }
    }

    /// The access token was rejected. Check it in Settings.
    static var errorUnauthorized: String {
        switch Localizer.current {
        case .english: "The access token was rejected. Check it in Settings."
        case .turkish: "Token reddedildi. Ayarlar'dan kontrol edin."
        }
    }

    /// Bitbucket is limiting requests. PR Checker will try again later.
    static var errorRateLimited: String {
        switch Localizer.current {
        case .english: "Bitbucket is limiting requests. PR Checker will try again later."
        case .turkish: "Bitbucket istekleri sınırlıyor. PR Checker daha sonra yeniden deneyecek."
        }
    }

    /// Bitbucket returned HTTP {code}.
    static func errorHTTP(code: Int) -> String {
        switch Localizer.current {
        case .english: "Bitbucket returned HTTP \(code)."
        case .turkish: "Bitbucket HTTP \(code) döndürdü."
        }
    }

    /// Unexpected response from Bitbucket.
    static var errorBadResponse: String {
        switch Localizer.current {
        case .english: "Unexpected response from Bitbucket."
        case .turkish: "Bitbucket'tan beklenmeyen bir yanıt geldi."
        }
    }

    /// Bitbucket returned an inconsistent page sequence.
    static var errorPaginationStalled: String {
        switch Localizer.current {
        case .english: "Bitbucket returned an inconsistent page sequence."
        case .turkish: "Bitbucket tutarsız bir sayfa sırası döndürdü."
        }
    }

    /// More than {limit} open pull requests; narrow it down with filters.
    static func errorTooManyResults(limit: Int) -> String {
        switch Localizer.current {
        case .english: "More than \(limit) open pull requests; narrow it down with filters."
        case .turkish: "\(limit) taneden fazla açık PR var; filtrelerle daraltın."
        }
    }

    /// Bitbucket sent an unexpectedly large response.
    static var errorResponseTooLarge: String {
        switch Localizer.current {
        case .english: "Bitbucket sent an unexpectedly large response."
        case .turkish: "Bitbucket beklenmedik derecede büyük bir yanıt gönderdi."
        }
    }

    /// Enter the access token for this server.
    static var errorTokenRequired: String {
        switch Localizer.current {
        case .english: "Enter the access token for this server."
        case .turkish: "Bu sunucunun token'ını girin."
        }
    }

    /// Enter a server URL like https://bitbucket.example.com.
    static var errorServerInvalid: String {
        switch Localizer.current {
        case .english: "Enter a server URL like https://bitbucket.example.com."
        case .turkish: "https://bitbucket.example.com gibi bir sunucu adresi girin."
        }
    }

    /// The server URL must start with https://.
    static var errorServerNotHTTPS: String {
        switch Localizer.current {
        case .english: "The server URL must start with https://."
        case .turkish: "Sunucu adresi https:// ile başlamalıdır."
        }
    }

    /// Remove the user name or password from the server URL.
    static var errorServerCredentials: String {
        switch Localizer.current {
        case .english: "Remove the user name or password from the server URL."
        case .turkish: "Sunucu adresinden kullanıcı adını veya parolayı kaldırın."
        }
    }

    /// Remove the ?query or #fragment from the server URL.
    static var errorServerQuery: String {
        switch Localizer.current {
        case .english: "Remove the ?query or #fragment from the server URL."
        case .turkish: "Sunucu adresinden ?sorgu veya #parça kısmını kaldırın."
        }
    }

    /// Signed out. Connect again in Settings → Bitbucket.
    static var signedOut: String {
        switch Localizer.current {
        case .english: "Signed out. Connect again in Settings → Bitbucket."
        case .turkish: "Oturum kapatıldı. Ayarlar → Bitbucket'tan yeniden bağlanın."
        }
    }

    /// Add your server URL and access token in Settings.
    static var notConfigured: String {
        switch Localizer.current {
        case .english: "Add your server URL and access token in Settings."
        case .turkish: "Sunucu adresinizi ve token'ınızı Ayarlar'dan ekleyin."
        }
    }

    /// Couldn't save the access token to the Keychain: {detail}
    static func keychainSaveFailed(detail: String) -> String {
        switch Localizer.current {
        case .english: "Couldn't save the access token to the Keychain: \(detail)"
        case .turkish: "Token Anahtar Zinciri'ne kaydedilemedi: \(detail)"
        }
    }
}
