// <auto-generated>Generated by shared/localization/generate.py from strings.json. Don't edit; change strings.json and rerun.</auto-generated>

namespace PRChecker.Core;

/// <summary>Every user-facing string, in the current <see cref="Localizer.Language"/>.</summary>
public static class L10n
{
    /// <summary>To review ({n})</summary>
    public static string ToReviewTab(int n) =>
        Localizer.Language == AppLanguage.Turkish
            ? $"İncelenecek ({n})"
            : $"To review ({n})";

    /// <summary>Mine ({n})</summary>
    public static string MineTab(int n) =>
        Localizer.Language == AppLanguage.Turkish
            ? $"PR'larım ({n})"
            : $"Mine ({n})";

    /// <summary>Nothing to review</summary>
    public static string NothingToReview =>
        Localizer.Language == AppLanguage.Turkish
            ? "İncelenecek bir şey yok"
            : "Nothing to review";

    /// <summary>No open pull requests</summary>
    public static string NoOpenPullRequests =>
        Localizer.Language == AppLanguage.Turkish
            ? "Açık PR yok"
            : "No open pull requests";

    /// <summary>Open Settings</summary>
    public static string OpenSettings =>
        Localizer.Language == AppLanguage.Turkish
            ? "Ayarları aç"
            : "Open Settings";

    /// <summary>Loading…</summary>
    public static string Loading =>
        Localizer.Language == AppLanguage.Turkish
            ? "Yükleniyor…"
            : "Loading…";

    /// <summary>Updated {time}</summary>
    public static string UpdatedAgo(string time) =>
        Localizer.Language == AppLanguage.Turkish
            ? $"{time} güncellendi"
            : $"Updated {time}";

    /// <summary>Refresh</summary>
    public static string Refresh =>
        Localizer.Language == AppLanguage.Turkish
            ? "Yenile"
            : "Refresh";

    /// <summary>Refresh (Ctrl+R)</summary>
    public static string RefreshShortcut =>
        Localizer.Language == AppLanguage.Turkish
            ? "Yenile (Ctrl+R)"
            : "Refresh (Ctrl+R)";

    /// <summary>Settings</summary>
    public static string Settings =>
        Localizer.Language == AppLanguage.Turkish
            ? "Ayarlar"
            : "Settings";

    /// <summary>Quit PR Checker</summary>
    public static string QuitApp =>
        Localizer.Language == AppLanguage.Turkish
            ? "PR Checker'dan çık"
            : "Quit PR Checker";

    /// <summary>Quit PR Checker?</summary>
    public static string QuitConfirmTitle =>
        Localizer.Language == AppLanguage.Turkish
            ? "PR Checker'dan çıkılsın mı?"
            : "Quit PR Checker?";

    /// <summary>You won't see pull requests or get notifications until you open it again.</summary>
    public static string QuitConfirmMessage =>
        Localizer.Language == AppLanguage.Turkish
            ? "Uygulamayı yeniden açana kadar PR'ları göremez ve bildirim almazsınız."
            : "You won't see pull requests or get notifications until you open it again.";

    /// <summary>Cancel</summary>
    public static string Cancel =>
        Localizer.Language == AppLanguage.Turkish
            ? "İptal"
            : "Cancel";

    /// <summary>Notifications are off in Windows Settings</summary>
    public static string NotificationsOffWindows =>
        Localizer.Language == AppLanguage.Turkish
            ? "Bildirimler Windows Ayarları'nda kapalı"
            : "Notifications are off in Windows Settings";

    /// <summary>Notifications aren't available on this PC</summary>
    public static string NotificationsUnavailablePC =>
        Localizer.Language == AppLanguage.Turkish
            ? "Bu bilgisayarda bildirimler kullanılamıyor"
            : "Notifications aren't available on this PC";

    /// <summary>Open notification settings</summary>
    public static string OpenNotificationSettings =>
        Localizer.Language == AppLanguage.Turkish
            ? "Bildirim ayarlarını aç"
            : "Open notification settings";

    /// <summary>Show Pull Requests</summary>
    public static string ShowPullRequests =>
        Localizer.Language == AppLanguage.Turkish
            ? "PR'ları göster"
            : "Show Pull Requests";

    /// <summary>PR Checker – {n} to review</summary>
    public static string TrayToReview(int n) =>
        Localizer.Language == AppLanguage.Turkish
            ? $"PR Checker – {n} incelenecek"
            : $"PR Checker – {n} to review";

    /// <summary>, one of yours needs attention</summary>
    public static string TrayAttention =>
        Localizer.Language == AppLanguage.Turkish
            ? ", PR'larınızdan birini kontrol etmeniz gerekiyor"
            : ", one of yours needs attention";

    /// <summary>PR Checker – not connected</summary>
    public static string TrayNotConnected =>
        Localizer.Language == AppLanguage.Turkish
            ? "PR Checker – bağlı değil"
            : "PR Checker – not connected";

    /// <summary>Draft</summary>
    public static string BadgeDraft =>
        Localizer.Language == AppLanguage.Turkish
            ? "Taslak"
            : "Draft";

    /// <summary>New commits</summary>
    public static string BadgeNewCommits =>
        Localizer.Language == AppLanguage.Turkish
            ? "Yeni commit'ler"
            : "New commits";

    /// <summary>Needs work</summary>
    public static string NeedsWork =>
        Localizer.Language == AppLanguage.Turkish
            ? "Değişiklik gerekli"
            : "Needs work";

    /// <summary>Conflicts</summary>
    public static string BadgeConflicts =>
        Localizer.Language == AppLanguage.Turkish
            ? "Çakışmalar"
            : "Conflicts";

    /// <summary>Build</summary>
    public static string BadgeBuild =>
        Localizer.Language == AppLanguage.Turkish
            ? "Derleme"
            : "Build";

    /// <summary>Approved</summary>
    public static string ReviewerApproved =>
        Localizer.Language == AppLanguage.Turkish
            ? "Onayladı"
            : "Approved";

    /// <summary>Not reviewed</summary>
    public static string ReviewerNotReviewed =>
        Localizer.Language == AppLanguage.Turkish
            ? "İncelemedi"
            : "Not reviewed";

    /// <summary>now</summary>
    public static string RelativeNow =>
        Localizer.Language == AppLanguage.Turkish
            ? "şimdi"
            : "now";

    /// <summary>{n} minutes ago</summary>
    public static string RelativeMinutes(int n) =>
        Localizer.Language == AppLanguage.Turkish
            ? $"{n} dakika önce"
            : n == 1 ? $"{n} minute ago" : $"{n} minutes ago";

    /// <summary>{n} hours ago</summary>
    public static string RelativeHours(int n) =>
        Localizer.Language == AppLanguage.Turkish
            ? $"{n} saat önce"
            : n == 1 ? $"{n} hour ago" : $"{n} hours ago";

    /// <summary>yesterday</summary>
    public static string RelativeYesterday =>
        Localizer.Language == AppLanguage.Turkish
            ? "dün"
            : "yesterday";

    /// <summary>{n} days ago</summary>
    public static string RelativeDays(int n) =>
        Localizer.Language == AppLanguage.Turkish
            ? $"{n} gün önce"
            : n == 1 ? $"{n} day ago" : $"{n} days ago";

    /// <summary>PR Checker Settings</summary>
    public static string SettingsWindowTitle =>
        Localizer.Language == AppLanguage.Turkish
            ? "PR Checker Ayarları"
            : "PR Checker Settings";

    /// <summary>General</summary>
    public static string TabGeneral =>
        Localizer.Language == AppLanguage.Turkish
            ? "Genel"
            : "General";

    /// <summary>Bitbucket</summary>
    public static string TabBitbucket =>
        Localizer.Language == AppLanguage.Turkish
            ? "Bitbucket"
            : "Bitbucket";

    /// <summary>About</summary>
    public static string TabAbout =>
        Localizer.Language == AppLanguage.Turkish
            ? "Hakkında"
            : "About";

    /// <summary>Notifications</summary>
    public static string Notifications =>
        Localizer.Language == AppLanguage.Turkish
            ? "Bildirimler"
            : "Notifications";

    /// <summary>Turned off in Windows Settings</summary>
    public static string BlockedWindowsTitle =>
        Localizer.Language == AppLanguage.Turkish
            ? "Windows Ayarları'nda kapalı"
            : "Turned off in Windows Settings";

    /// <summary>Windows is blocking PR Checker's notifications. Turn them on for PR Checker.</summary>
    public static string BlockedWindowsMessage =>
        Localizer.Language == AppLanguage.Turkish
            ? "Windows, PR Checker bildirimlerini engelliyor. PR Checker için bildirimleri açın."
            : "Windows is blocking PR Checker's notifications. Turn them on for PR Checker.";

    /// <summary>Not available on this PC</summary>
    public static string UnavailableTitle =>
        Localizer.Language == AppLanguage.Turkish
            ? "Bu bilgisayarda kullanılamıyor"
            : "Not available on this PC";

    /// <summary>Windows couldn't set up notifications for PR Checker ({reason}). Pull requests still show in the tray.</summary>
    public static string UnavailableMessage(string reason) =>
        Localizer.Language == AppLanguage.Turkish
            ? $"Windows, PR Checker için bildirimleri ayarlayamadı ({reason}). PR'lar sistem tepsisinde görünmeye devam eder."
            : $"Windows couldn't set up notifications for PR Checker ({reason}). Pull requests still show in the tray.";

    /// <summary>Send Test Notification</summary>
    public static string SendTestNotification =>
        Localizer.Language == AppLanguage.Turkish
            ? "Test bildirimi gönder"
            : "Send Test Notification";

    /// <summary>Show pull request details in notifications</summary>
    public static string ShowDetailsInNotifications =>
        Localizer.Language == AppLanguage.Turkish
            ? "Bildirimlerde PR ayrıntılarını göster"
            : "Show pull request details in notifications";

    /// <summary>Off: notifications don't show titles, names or results, e.g. while screen sharing.</summary>
    public static string ShowDetailsHint =>
        Localizer.Language == AppLanguage.Turkish
            ? "Kapalıyken bildirimler başlık, isim veya sonuç göstermez; örneğin ekran paylaşırken."
            : "Off: notifications don't show titles, names or results, e.g. while screen sharing.";

    /// <summary>Open at login</summary>
    public static string OpenAtLogin =>
        Localizer.Language == AppLanguage.Turkish
            ? "Oturum açılınca başlat"
            : "Open at login";

    /// <summary>Check every</summary>
    public static string CheckEvery =>
        Localizer.Language == AppLanguage.Turkish
            ? "Kontrol sıklığı"
            : "Check every";

    /// <summary>{n} min</summary>
    public static string MinutesShort(int n) =>
        Localizer.Language == AppLanguage.Turkish
            ? $"{n} dk"
            : $"{n} min";

    /// <summary>Language</summary>
    public static string Language =>
        Localizer.Language == AppLanguage.Turkish
            ? "Dil"
            : "Language";

    /// <summary>System language</summary>
    public static string LanguageSystem =>
        Localizer.Language == AppLanguage.Turkish
            ? "Sistem dili"
            : "System language";

    /// <summary>Server URL</summary>
    public static string ServerURL =>
        Localizer.Language == AppLanguage.Turkish
            ? "Sunucu adresi"
            : "Server URL";

    /// <summary>Access token</summary>
    public static string AccessToken =>
        Localizer.Language == AppLanguage.Turkish
            ? "Token"
            : "Access token";

    /// <summary>Saved – leave empty to keep</summary>
    public static string TokenSavedPlaceholder =>
        Localizer.Language == AppLanguage.Turkish
            ? "Kayıtlı – değiştirmemek için boş bırakın"
            : "Saved – leave empty to keep";

    /// <summary>Required</summary>
    public static string TokenRequiredPlaceholder =>
        Localizer.Language == AppLanguage.Turkish
            ? "Gerekli"
            : "Required";

    /// <summary>Save &amp; Connect</summary>
    public static string SaveAndConnect =>
        Localizer.Language == AppLanguage.Turkish
            ? "Kaydet ve bağlan"
            : "Save & Connect";

    /// <summary>Connected as {name}</summary>
    public static string ConnectedAs(string name) =>
        Localizer.Language == AppLanguage.Turkish
            ? $"{name} olarak bağlanıldı"
            : $"Connected as {name}";

    /// <summary>Couldn't reach the server: {message}</summary>
    public static string CouldntReachServer(string message) =>
        Localizer.Language == AppLanguage.Turkish
            ? $"Sunucuya ulaşılamadı: {message}"
            : $"Couldn't reach the server: {message}";

    /// <summary>Sign Out</summary>
    public static string SignOut =>
        Localizer.Language == AppLanguage.Turkish
            ? "Oturumu kapat"
            : "Sign Out";

    /// <summary>Sign out of Bitbucket?</summary>
    public static string SignOutConfirmTitle =>
        Localizer.Language == AppLanguage.Turkish
            ? "Bitbucket oturumu kapatılsın mı?"
            : "Sign out of Bitbucket?";

    /// <summary>Removes the access token from Credential Manager and the pull request data PR Checker stored for this server.</summary>
    public static string SignOutConfirmMessageWindows =>
        Localizer.Language == AppLanguage.Turkish
            ? "Bu sunucunun token'ını Kimlik Bilgileri Yöneticisi'nden ve PR Checker'ın sakladığı PR verilerini siler."
            : "Removes the access token from Credential Manager and the pull request data PR Checker stored for this server.";

    /// <summary>Create a token under Profile → Manage account → HTTP access tokens with Read permission. It is stored in Windows Credential Manager and only sent to this server.</summary>
    public static string TokenHintWindows =>
        Localizer.Language == AppLanguage.Turkish
            ? "Bitbucket'ta Profile → Manage account → HTTP access tokens altında Read izinli bir token oluşturun. Token Windows Kimlik Bilgileri Yöneticisi'nde saklanır ve yalnızca bu sunucuya gönderilir."
            : "Create a token under Profile → Manage account → HTTP access tokens with Read permission. It is stored in Windows Credential Manager and only sent to this server.";

    /// <summary>Filters</summary>
    public static string Filters =>
        Localizer.Language == AppLanguage.Turkish
            ? "Filtreler"
            : "Filters";

    /// <summary>Hide draft pull requests</summary>
    public static string HideDrafts =>
        Localizer.Language == AppLanguage.Turkish
            ? "Taslak PR'ları gizle"
            : "Hide draft pull requests";

    /// <summary>Only these projects/repos</summary>
    public static string OnlyTheseRepos =>
        Localizer.Language == AppLanguage.Turkish
            ? "Yalnızca bu projeler/repolar"
            : "Only these projects/repos";

    /// <summary>All</summary>
    public static string FilterAllPlaceholder =>
        Localizer.Language == AppLanguage.Turkish
            ? "Tümü"
            : "All";

    /// <summary>Comma-separated project keys or PROJECT/repo-slug, e.g. PROJ, OTHER/my-repo.</summary>
    public static string FilterHint =>
        Localizer.Language == AppLanguage.Turkish
            ? "Virgülle ayrılmış proje anahtarları veya PROJE/repo-slug, örn. PROJ, OTHER/my-repo."
            : "Comma-separated project keys or PROJECT/repo-slug, e.g. PROJ, OTHER/my-repo.";

    /// <summary>Check for Updates</summary>
    public static string CheckForUpdates =>
        Localizer.Language == AppLanguage.Turkish
            ? "Güncellemeleri kontrol et"
            : "Check for Updates";

    /// <summary>Last checked {time}</summary>
    public static string LastChecked(string time) =>
        Localizer.Language == AppLanguage.Turkish
            ? $"Son kontrol: {time}"
            : $"Last checked {time}";

    /// <summary>Checked automatically once a week</summary>
    public static string CheckedWeekly =>
        Localizer.Language == AppLanguage.Turkish
            ? "Haftada bir otomatik kontrol edilir"
            : "Checked automatically once a week";

    /// <summary>PR Checker is up to date.</summary>
    public static string UpToDate =>
        Localizer.Language == AppLanguage.Turkish
            ? "PR Checker güncel."
            : "PR Checker is up to date.";

    /// <summary>Updates are only available in installed builds.</summary>
    public static string UpdatesOnlyInstalled =>
        Localizer.Language == AppLanguage.Turkish
            ? "Güncellemeler yalnızca kurulu sürümlerde kullanılabilir."
            : "Updates are only available in installed builds.";

    /// <summary>Couldn't check for updates: {message}</summary>
    public static string CouldntCheckUpdates(string message) =>
        Localizer.Language == AppLanguage.Turkish
            ? $"Güncellemeler kontrol edilemedi: {message}"
            : $"Couldn't check for updates: {message}";

    /// <summary>Update available</summary>
    public static string UpdateAvailableTitle =>
        Localizer.Language == AppLanguage.Turkish
            ? "Güncelleme var"
            : "Update available";

    /// <summary>PR Checker {latest} is available. You have {current}.  Install it now? PR Checker restarts when it's done.</summary>
    public static string UpdateAvailableMessage(string latest, string current) =>
        Localizer.Language == AppLanguage.Turkish
            ? $"PR Checker {latest} yayımlandı. Sizdeki sürüm: {current}.\n\nŞimdi kurulsun mu? Kurulum bitince PR Checker yeniden başlar."
            : $"PR Checker {latest} is available. You have {current}.\n\nInstall it now? PR Checker restarts when it's done.";

    /// <summary>Review requested by {author}</summary>
    public static string NotifyReviewRequested(string author) =>
        Localizer.Language == AppLanguage.Turkish
            ? $"{author} inceleme istedi"
            : $"Review requested by {author}";

    /// <summary>New commits to re-review</summary>
    public static string NotifyNewCommits =>
        Localizer.Language == AppLanguage.Turkish
            ? "Yeniden incelenecek yeni commit'ler"
            : "New commits to re-review";

    /// <summary>✅ Approved by {name}</summary>
    public static string NotifyApproved(string name) =>
        Localizer.Language == AppLanguage.Turkish
            ? $"✅ {name} onayladı"
            : $"✅ Approved by {name}";

    /// <summary>✋ {name} marked it needs work</summary>
    public static string NotifyNeedsWork(string name) =>
        Localizer.Language == AppLanguage.Turkish
            ? $"✋ {name} değişiklik istedi"
            : $"✋ {name} marked it needs work";

    /// <summary>⚠️ Merge conflicts</summary>
    public static string NotifyConflicts =>
        Localizer.Language == AppLanguage.Turkish
            ? "⚠️ Birleştirme çakışmaları"
            : "⚠️ Merge conflicts";

    /// <summary>🔧 Conflicts resolved</summary>
    public static string NotifyConflictsResolved =>
        Localizer.Language == AppLanguage.Turkish
            ? "🔧 Çakışmalar çözüldü"
            : "🔧 Conflicts resolved";

    /// <summary>❌ Build failed</summary>
    public static string NotifyBuildFailed =>
        Localizer.Language == AppLanguage.Turkish
            ? "❌ Derleme başarısız"
            : "❌ Build failed";

    /// <summary>✅ Build fixed</summary>
    public static string NotifyBuildFixed =>
        Localizer.Language == AppLanguage.Turkish
            ? "✅ Derleme düzeldi"
            : "✅ Build fixed";

    /// <summary>💬 {n} new comments from {names}</summary>
    public static string NotifyComments(int n, string names) =>
        Localizer.Language == AppLanguage.Turkish
            ? $"💬 {n} yeni yorum: {names}"
            : n == 1 ? $"💬 {n} new comment from {names}" : $"💬 {n} new comments from {names}";

    /// <summary>🎉 Merged</summary>
    public static string NotifyMerged =>
        Localizer.Language == AppLanguage.Turkish
            ? "🎉 Birleştirildi"
            : "🎉 Merged";

    /// <summary>🚫 Declined</summary>
    public static string NotifyDeclined =>
        Localizer.Language == AppLanguage.Turkish
            ? "🚫 Reddedildi"
            : "🚫 Declined";

    /// <summary>No longer open</summary>
    public static string NotifyNoLongerOpen =>
        Localizer.Language == AppLanguage.Turkish
            ? "Artık açık değil"
            : "No longer open";

    /// <summary>PR Checker notifications work</summary>
    public static string TestNotificationTitle =>
        Localizer.Language == AppLanguage.Turkish
            ? "PR Checker bildirimleri çalışıyor"
            : "PR Checker notifications work";

    /// <summary>Click a notification to open its pull request.</summary>
    public static string TestNotificationBody =>
        Localizer.Language == AppLanguage.Turkish
            ? "PR'ı açmak için bildirime tıklayın."
            : "Click a notification to open its pull request.";

    /// <summary>A pull request has an update. Click to open it.</summary>
    public static string PrivateNotificationBody =>
        Localizer.Language == AppLanguage.Turkish
            ? "Bir PR'da güncelleme var. Açmak için tıklayın."
            : "A pull request has an update. Click to open it.";

    /// <summary>The access token was rejected. Check it in Settings.</summary>
    public static string ErrorUnauthorized =>
        Localizer.Language == AppLanguage.Turkish
            ? "Token reddedildi. Ayarlar'dan kontrol edin."
            : "The access token was rejected. Check it in Settings.";

    /// <summary>Bitbucket is limiting requests. PR Checker will try again later.</summary>
    public static string ErrorRateLimited =>
        Localizer.Language == AppLanguage.Turkish
            ? "Bitbucket istekleri sınırlıyor. PR Checker daha sonra yeniden deneyecek."
            : "Bitbucket is limiting requests. PR Checker will try again later.";

    /// <summary>Bitbucket returned HTTP {code}.</summary>
    public static string ErrorHTTP(int code) =>
        Localizer.Language == AppLanguage.Turkish
            ? $"Bitbucket HTTP {code} döndürdü."
            : $"Bitbucket returned HTTP {code}.";

    /// <summary>Unexpected response from Bitbucket.</summary>
    public static string ErrorBadResponse =>
        Localizer.Language == AppLanguage.Turkish
            ? "Bitbucket'tan beklenmeyen bir yanıt geldi."
            : "Unexpected response from Bitbucket.";

    /// <summary>Bitbucket returned an inconsistent page sequence.</summary>
    public static string ErrorPaginationStalled =>
        Localizer.Language == AppLanguage.Turkish
            ? "Bitbucket tutarsız bir sayfa sırası döndürdü."
            : "Bitbucket returned an inconsistent page sequence.";

    /// <summary>More than {limit} open pull requests; narrow it down with filters.</summary>
    public static string ErrorTooManyResults(int limit) =>
        Localizer.Language == AppLanguage.Turkish
            ? $"{limit} taneden fazla açık PR var; filtrelerle daraltın."
            : $"More than {limit} open pull requests; narrow it down with filters.";

    /// <summary>Bitbucket sent an unexpectedly large response.</summary>
    public static string ErrorResponseTooLarge =>
        Localizer.Language == AppLanguage.Turkish
            ? "Bitbucket beklenmedik derecede büyük bir yanıt gönderdi."
            : "Bitbucket sent an unexpectedly large response.";

    /// <summary>Enter the access token for this server.</summary>
    public static string ErrorTokenRequired =>
        Localizer.Language == AppLanguage.Turkish
            ? "Bu sunucunun token'ını girin."
            : "Enter the access token for this server.";

    /// <summary>Enter a server URL like https://bitbucket.example.com.</summary>
    public static string ErrorServerInvalid =>
        Localizer.Language == AppLanguage.Turkish
            ? "https://bitbucket.example.com gibi bir sunucu adresi girin."
            : "Enter a server URL like https://bitbucket.example.com.";

    /// <summary>The server URL must start with https://.</summary>
    public static string ErrorServerNotHTTPS =>
        Localizer.Language == AppLanguage.Turkish
            ? "Sunucu adresi https:// ile başlamalıdır."
            : "The server URL must start with https://.";

    /// <summary>Remove the user name or password from the server URL.</summary>
    public static string ErrorServerCredentials =>
        Localizer.Language == AppLanguage.Turkish
            ? "Sunucu adresinden kullanıcı adını veya parolayı kaldırın."
            : "Remove the user name or password from the server URL.";

    /// <summary>Remove the ?query or #fragment from the server URL.</summary>
    public static string ErrorServerQuery =>
        Localizer.Language == AppLanguage.Turkish
            ? "Sunucu adresinden ?sorgu veya #parça kısmını kaldırın."
            : "Remove the ?query or #fragment from the server URL.";

    /// <summary>Signed out. Connect again in Settings → Bitbucket.</summary>
    public static string SignedOut =>
        Localizer.Language == AppLanguage.Turkish
            ? "Oturum kapatıldı. Ayarlar → Bitbucket'tan yeniden bağlanın."
            : "Signed out. Connect again in Settings → Bitbucket.";

    /// <summary>Add your server URL and access token in Settings.</summary>
    public static string NotConfigured =>
        Localizer.Language == AppLanguage.Turkish
            ? "Sunucu adresinizi ve token'ınızı Ayarlar'dan ekleyin."
            : "Add your server URL and access token in Settings.";

    /// <summary>Couldn't reach Bitbucket: {message}</summary>
    public static string CouldntReachBitbucket(string message) =>
        Localizer.Language == AppLanguage.Turkish
            ? $"Bitbucket'a ulaşılamadı: {message}"
            : $"Couldn't reach Bitbucket: {message}";

    /// <summary>Refresh failed: {message}</summary>
    public static string RefreshFailed(string message) =>
        Localizer.Language == AppLanguage.Turkish
            ? $"Yenileme başarısız: {message}"
            : $"Refresh failed: {message}";

    /// <summary>Couldn't save the access token in Credential Manager: {detail}</summary>
    public static string CredentialSaveFailed(string detail) =>
        Localizer.Language == AppLanguage.Turkish
            ? $"Token Kimlik Bilgileri Yöneticisi'ne kaydedilemedi: {detail}"
            : $"Couldn't save the access token in Credential Manager: {detail}";

    /// <summary>Couldn't delete the access token in Credential Manager: {detail}</summary>
    public static string CredentialDeleteFailed(string detail) =>
        Localizer.Language == AppLanguage.Turkish
            ? $"Token Kimlik Bilgileri Yöneticisi'nden silinemedi: {detail}"
            : $"Couldn't delete the access token in Credential Manager: {detail}";

    /// <summary>PR Checker couldn't start.  {error}  Details are in: {path}</summary>
    public static string StartupFailed(string error, string path) =>
        Localizer.Language == AppLanguage.Turkish
            ? $"PR Checker başlatılamadı.\n\n{error}\n\nAyrıntılar şurada:\n{path}"
            : $"PR Checker couldn't start.\n\n{error}\n\nDetails are in:\n{path}";
}
